version: '3.7'

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.minelast.de`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    restart: always
     
networks:
  traefik_proxy:
    external:
      name: traefik_proxy