version: '3.7'

services:
  whoami:
    image: containous/whoami:${image_tag}
    container_name: whoami
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(${domain})"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=lets-encrypt"
      - "traefik.http.services.whoami-whoami.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
