version: "3.7"

services:
    endlessh:
        image: harshavardhanj/endlessh:${image_tag}
        container_name: endlessh
        ports:
        - "${outgoing_port}:2222"
        restart: unless-stopped
