version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:${image_tag}
    volumes:
      - ${data_folder}:/data
    environment:
      WEBSOCKET_ENABLED: ${websocket}
      SIGNUPS_ALLOWED: ${signups}   # set to false to disable signups
      ADMIN_TOKEN: ${admintoken}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.rule=Host(${domain})"
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.routers.bitwarden.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
      - "docker-volume-backup.stop-during-backup=true"
    restart: unless-stopped


networks:
  traefik_proxy:
    external:
      name: traefik_proxy
