version: '3.7'

services:
  whoami:
    image: statping/statping:${image_tag}
    container_name: statping
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.statping.rule=Host(`statping.minelast.de`, `status.minelast.de`)"
      - "traefik.http.routers.statping.tls=true"
      - "traefik.http.routers.statping.tls.certresolver=lets-encrypt"
      - "traefik.port=8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${data_folder}:/app
    environment:
      DB_CONN: sqlite
    restart: unless-stopped

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
