version : '3'

services:
  mysql:
    image: mysql:${mysql_image_tag}
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${mysql_outgoing_port}:3306
    networks:
      - mysqlnet
    environment:
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_user_pw}
      MYSQL_ROOT_PASSWORD: ${mysql_root_pw}
      MYSQL_DATABASE: default_schema
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${pma_image_tag}
    depends_on:
      - mysql
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql:${mysql_outgoing_port}
      PMA_PORT: ${mysql_outgoing_port}
    networks:
      - mysqlnet
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(${domain})"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=lets-encrypt"
      - "traefik.port=80"
    restart: unless-stopped

networks:
  mysqlnet:
  traefik_proxy:
    external:
      name: traefik_proxy
