[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$DgeAEs0W$oXvBo8hgPfb2h2KKyMzqc1"
  ]
  
[http.routers.api]
  rule = "Host(`traefik.minelast.de`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"