[log]
  level = "INFO"
    
	
[providers.docker]
  watch = true
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik_proxy"

[providers.file]
  filename = "/etc/traefik/dynamic.toml"
    
[api]
  dashboard = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
	
[certificatesResolvers.lets-encrypt.acme]
  email = "admin@minelast.de"
  storage = "/etc/traefik/ACME/acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]
	
