services:
  mc:
    image: itzg/minecraft-server
    container_name: mc_testserver
    ports:
      - 25566:25565
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data/:/data
