services:
  mc:
    image: itzg/minecraft-server:${image_tag}
    container_name: mc_gameserver
    ports:
      - ${outgoing_port}:25565
    environment:
      EULA: "TRUE"
      TYPE: ${server_type}
      SPIGOT_DOWNLOAD_URL: ${spigot_url}
      MEMORY: ${server_memory}
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ${data_folder}:/data
    # enables console, use: docker attach <DOCKER-CONTAINER> 
    stdin_open: true
    tty: true
